### ISSUE TITLE
Autodeal and extra_wait question.

### ISSUE THREAD

**Issue by AeonLerau** [pokermania/pokernetwork#3]
Hi,

Can you explain what the following delays In poker.server.xml are designed to accomplish.  I don't have a client yet to test these but I am curious of how they are meant to be used and how they affect the game play. 
autodeal_tournament_min="15"
extra_wait_sng_start="30"
extra_wait_tourney_start="60"

cheers

**Comment by hwmrocker** [comment]
Sure,

**autodeal_tournament_min** is the time in seconds, a hand should last at least during a tournament. It is a safe guard when there are only bots/auto_players because of connection problems. If this value is 0 it would be possible that the tourney would be finished in an instant. It could produce a greedy loop that will also exhaust all CPU power until it is finished.

The **extra_wait_..._start** value tells the network to wait additional amount of seconds before starting the tournament/sng for missing players. It would be safe to set these values to 0.
